// Generated by: main
// TypeWriter: set
// Directive: +gen on Value

package core

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// The primary type that represents a set
type ValueSet map[Value]struct{}

// Creates and returns a reference to an empty set.
func NewValueSet(a ...Value) ValueSet {
	s := make(ValueSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set ValueSet) ToSlice() []Value {
	var s []Value
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set ValueSet) Add(i Value) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set ValueSet) Contains(i Value) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set ValueSet) ContainsAll(i ...Value) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// Determines if every item in the other set is in this set.
func (set ValueSet) IsSubset(other ValueSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set ValueSet) IsSuperset(other ValueSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set ValueSet) Union(other ValueSet) ValueSet {
	unionedSet := NewValueSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set ValueSet) Intersect(other ValueSet) ValueSet {
	intersection := NewValueSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set ValueSet) Difference(other ValueSet) ValueSet {
	differencedSet := NewValueSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set ValueSet) SymmetricDifference(other ValueSet) ValueSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *ValueSet) Clear() {
	*set = make(ValueSet)
}

// Allows the removal of a single item in the set.
func (set ValueSet) Remove(i Value) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set ValueSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type Value that you can range over.
func (set ValueSet) Iter() <-chan Value {
	ch := make(chan Value)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set ValueSet) Equal(other ValueSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set ValueSet) Clone() ValueSet {
	clonedSet := NewValueSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
